# golangci-lint configuration for v2
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: "1.24"

linters:
  enable:
    - errcheck # Check for unchecked errors
    - govet # Vet examines Go source code
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Static analysis checks (includes gosimple)
    - unused # Check for unused constants, variables, functions and types
    - misspell # Find commonly misspelled words
    - revive # Fast, configurable, extensible linter
    - gosec # Security-focused linter
    - unconvert # Remove unnecessary type conversions
    - unparam # Find unused function parameters
    - goconst # Find repeated strings that could be constants
    - gocyclo # Check cyclomatic complexity
    - dupl # Check for code duplication
    - prealloc # Find slice declarations that could be preallocated
    - copyloopvar # Check for loop variable copies (replaces exportloopref)
    - nilerr # Find code that returns nil even if it checks that error is not nil
    - bodyclose # Check HTTP response body is closed
    - noctx # Find sending HTTP request without context.Context
    - rowserrcheck # Check whether Err of rows is checked successfully
    - sqlclosecheck # Check that sql.Rows and sql.Stmt are closed
    - gocritic # Additional diagnostics for bugs, performance and style

formatters:
  enable:
    - gofmt # Format code
    - goimports # Format imports

linters-config:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: var-naming
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning

  gosec:
    excludes:
      - G104 # Audit errors not checked - covered by errcheck

  misspell:
    locale: US

  goconst:
    min-len: 3
    min-occurrences: 3

issues-config:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst

    # Exclude known false positives
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

    # Allow dot imports in tests for testify
    - path: _test\.go
      text: "dot imports"
      linters:
        - revive

output-config:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
